# Generated by Django 3.1.2 on 2020-10-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20201010_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
