# Generated by Django 3.1.2 on 2020-10-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20201014_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['start_date'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['start_date'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
    ]
