# Generated by Django 3.1.2 on 2020-10-19 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_remove_staff_subject'),
        ('course', '0010_remove_subject_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject', to='staff.staff'),
        ),
    ]
