# Generated by Django 3.1.2 on 2020-11-09 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_remove_staff_subject'),
        ('course', '0011_subject_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='course.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='staff.staff'),
        ),
    ]
