# Generated by Django 3.1.2 on 2020-10-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20201009_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='recruitment_date',
            field=models.DateField(null=True),
        ),
    ]
