# Generated by Django 3.1.2 on 2020-10-19 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_remove_subject_staff'),
        ('staff', '0009_auto_20201012_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.subject'),
        ),
    ]
