# Generated by Django 3.1.2 on 2020-10-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20201019_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='subject',
        ),
    ]
