# Generated by Django 3.1.2 on 2020-11-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_remove_staff_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['user__full_name'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staffs'},
        ),
    ]
