# Generated by Django 3.1.2 on 2020-11-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20201119_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(max_length=17, null=True),
        ),
    ]
