# Generated by Django 2.2.19 on 2021-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_staff_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['user__full_name'], 'verbose_name_plural': 'Staffs'},
        ),
        migrations.AlterField(
            model_name='staff',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
