# Generated by Django 3.1.2 on 2020-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
