# Generated by Django 3.1.2 on 2020-11-04 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_auto_20201102_2020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSeenAnnouncement',
        ),
    ]
