# Generated by Django 3.1.2 on 2020-11-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhod', '0002_auto_20201118_1949'),
        ('feedback', '0003_auto_20201027_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackstudent',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='feedbackstudent',
            name='is_seen',
            field=models.ManyToManyField(blank=True, related_name='seen_student_feedbacks', to='adminhod.AdminHOD'),
        ),
    ]
