# Generated by Django 3.1.2 on 2020-11-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhod', '0002_auto_20201118_1949'),
        ('feedback', '0004_auto_20201119_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackstaff',
            name='is_seen',
        ),
        migrations.AddField(
            model_name='feedbackstaff',
            name='is_seen',
            field=models.ManyToManyField(blank=True, related_name='seen_staff_feedbacks', to='adminhod.AdminHOD'),
        ),
    ]
