# Generated by Django 3.1.2 on 2020-10-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('staff_user', models.BooleanField(default=False)),
                ('superuser', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_type', models.CharField(choices=[('HOD', 'HOD'), ('STAFF', 'Staff'), ('STUDENT', 'Student')], default='HOD', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
