# Generated by Django 3.1.2 on 2020-11-01 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='previously_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
