# Generated by Django 3.1.2 on 2020-10-14 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_sessionyear'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionyear',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AddField(
            model_name='sessionyear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionyear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
