# Generated by Django 3.1.2 on 2020-10-14 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20201014_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admission_date',
        ),
        migrations.AddField(
            model_name='student',
            name='session_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.sessionyear'),
        ),
    ]
