# Generated by Django 3.1.2 on 2020-10-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20201014_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessionyear',
            options={'ordering': ['start_date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['session_year__start_date'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
