# Generated by Django 3.1.2 on 2020-11-19 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_sessionyear_date_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__full_name'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
    ]
