# Generated by Django 3.1.2 on 2020-11-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_auto_20201120_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
