# Generated by Django 2.2.19 on 2021-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_student_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__full_name']},
        ),
        migrations.AlterField(
            model_name='student',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
