# Generated by Django 3.1.2 on 2020-11-18 17:49

import adminhod.models
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adminhod', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminhod',
            name='address',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='nationality',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminhod',
            name='phone',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='photo',
            field=models.ImageField(default='user_default.jpg', upload_to=adminhod.models.adminhod_image),
        ),
        migrations.AddField(
            model_name='adminhod',
            name='recruitment_date',
            field=models.DateField(null=True),
        ),
    ]
