# Generated by Django 3.1.2 on 2020-11-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminhod', '0002_auto_20201118_1949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminhod',
            options={'ordering': ['user__full_name'], 'verbose_name': 'AdminHOD', 'verbose_name_plural': 'AdminHODs'},
        ),
    ]
