# Generated by Django 2.2.19 on 2021-05-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminhod', '0005_adminhod_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='adminhod',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
