# Generated by Django 3.1.2 on 2020-11-09 18:52

import assignment.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0012_auto_20201109_1437'),
        ('student', '0014_sessionyear_date_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('assignment', models.FileField(blank=True, null=True, upload_to=assignment.models.student_assignment)),
                ('deadline_date', models.DateField()),
                ('is_submitted', models.BooleanField(blank=True, default=False, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.ManyToManyField(blank=True, related_name='seen_assignments', to='student.Student')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.sessionyear')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'ordering': ['-created_at'],
            },
        ),
    ]
