# Generated by Django 3.1.2 on 2020-11-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20201109_1437'),
        ('student', '0014_sessionyear_date_range'),
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentAssignment',
            new_name='Assignment',
        ),
    ]
