# Generated by Django 3.1.2 on 2020-11-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_auto_20201109_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='is_submitted',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='student',
        ),
    ]
