# Generated by Django 3.1.2 on 2020-11-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_sessionyear_date_range'),
        ('assignment', '0006_auto_20201109_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_submitted',
            field=models.ManyToManyField(blank=True, related_name='submitted_assignments', to='student.Student'),
        ),
    ]
