# Generated by Django 3.1.2 on 2020-11-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_assignment_is_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
