# Generated by Django 3.1.2 on 2020-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_assignment_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='allow_submission_after_deadline',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
