# Generated by Django 3.1.2 on 2020-11-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0009_assignment_allow_submission_after_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_seen_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
