# Generated by Django 3.1.2 on 2020-10-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['attendance_date'], 'verbose_name': 'Attendance', 'verbose_name_plural': 'Attendance'},
        ),
        migrations.AlterModelOptions(
            name='attendancereport',
            options={'ordering': ['attendance__attendance_date'], 'verbose_name': 'Attendance Report', 'verbose_name_plural': 'Attendance Reports'},
        ),
    ]
